apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searching4hope-domain-reclamation
  description: Testing
  annotations:
    circleci.com/project-slug: github/coombsj/searching4hope-domain-reclamation
    github.com/project-slug: coombsj/searching4hope-domain-reclamation
  labels:
    data-classification: public
  tags:
    - teraform
spec:
  type: service
  lifecycle: experimental
  owner: coombsj
